job-application-manojsharma/config/routes.rb
# frozen_string_literal:true

Rails.application.routes.draw do
  resources :apply_jobs, only: %i[create destroy]
  resources :jobs
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/contact'
  get 'static_pages/dashbord_users'
  get 'static_pages/about'
  devise_for :users, controllers: {
    sessions: 'devise/sessions'
    # registrations: 'devise/registrations'

  }
  resources :user_profiles, only: %i[show destroy]
  resources :users
end

job-application-manojsharma/app/controllers/static_pages_controller.rb
# frozen_string_literal:true

# class for static pages
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  # root_path  static_pages/home
  def home
    if user_signed_in? && (current_user.user_role.include? 'Employer')
      @jobs = Job.where(user_id: current_user.id)
      @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(7)
      jobs_ids = Job.where(user_id: current_user.id).pluck(:id)
      apply_user_ids = ApplyJob.where('job_id IN (?)', jobs_ids).pluck(:user_id).uniq
      @user_apply = User.where(id: apply_user_ids)
    end
    # current_user.admin == false or !current_user.admin
    if user_signed_in? && (current_user.user_role.include? 'Job Seeker') && !current_user.admin
      @jobs = Job.all
      @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(7)
    end

    if user_signed_in? && current_user.admin
      @jobs = Job.all
      @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(7)
    end
  end

  def help; end

  def contact; end

  def about; end

  # static_pages_dashbord_users_path   static_pages/dashbord_users
  def dashbord_users
    @users = User.all
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(5)
  end
end

job-application-manojsharma/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

job-application-manojsharma/app/views/static_pages/_adminview.html.erb
<h4 style="text-decoration:underline">List Of Jobs</h4>
 
<table class="table table-hover">
  <thead>
    <tr>
     <th>User ID</th>
      <th>Job title</th>
      <th>Experience</th>
      <th>Salary</th>
      
        <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
       <td><%= job.user_id %></td>
        <td><%= job.job_title %></td>
        <td><%= job.experience %></td>
        <td><%= job.salary %></td>
       
         <td><%= job.description %></td>
        <td><%= link_to 'Show', job ,class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_job_path(job) , class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @jobs , theme: 'my_custom_theme'  %>

job-application-manojsharma/app/views/static_pages/_carasole.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("/assets/2.jpeg", :alt => "logo",class:"d-block w-100") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("/assets/3.jpeg", :alt => "logo",class:"d-block w-100") %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("/assets/OIP.jpeg", :alt => "logo",class:"d-block w-100") %>
     <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

job-application-manojsharma/app/views/static_pages/_employerview.html.erb
<div class="container container-fluid">
   <h4>Jobs Created</h4>
   <%= link_to "Create New Job ", new_job_path , class:"btn btn-primary"%>
   <br>
   <table class="table table-hover">
      <thead>
         <tr>
            <th>Job title</th>
            <th>Experience</th>
            <th>Salary</th>
            <th>Description</th>
            <th colspan="3" class="text-center"> Options</th>
         </tr>
      </thead>
      <tbody>
         <% @jobs.each do |job| %>
         <tr>
            <td><%= job.job_title %></td>
            <td><%= job.experience %></td>
            <td><%= job.salary %></td>
            <td><%= job.description %></td>
            <td><%= link_to 'Show', job  ,class:"btn btn-info"%></td>
            <td><%= link_to 'Edit', edit_job_path(job) ,class:"btn btn-warning"%></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
         </tr>
         <% end %>
      </tbody>
   </table>
   <%= paginate @jobs , theme: 'my_custom_theme' %>
</div>

job-application-manojsharma/app/views/static_pages/_jobapplyempview.html.erb
<h1>Jobs Created</h1>
<table class="table table-hover">
   <thead>
      <tr>
         <th>Name </th>
         <th>Email</th>
         <th>Mobile No.</th>
         <th colspan="3"></th>
      </tr>
   </thead>
   <tbody>
      <% @user_apply.each do |user_apply| %>
      <tr>
         <td><%= user_apply.first_name %></td>
         <td><%= user_apply.email %></td>
         <td><%= user_apply.mobile_no %></td>
      </tr>
      <% end %>
   </tbody>
</table>

job-application-manojsharma/app/views/static_pages/_jobseekerview.html.erb
<hr>
<div class="container continer-fluid">
   <h3> All Jobs</h3>
   <table class="table table-hover table-bordered">
      <thead>
         <tr>
            <th>Job title</th>
            <th>Experience</th>
            <th>Salary</th>
            <th>Job Details</th>
            <th>Application Status</th>
         </tr>
      </thead>
      <tbody>
         <% @jobs.each do |job| %>
         <tr>
            <td><%= job.job_title %></td>
            <td><%= job.experience %></td>
            <td><%= job.salary %></td>
            <td><%= link_to 'Show', job , class:"btn btn-warning" %></td>
            <%if applied_to_job?(current_user.id,job.id) %>
            <td><%= link_to 'Applied Already', job ,class:"btn btn-success"%></td>
            <%else%>
            <td><%= link_to 'Apply Now', job ,class:"btn btn-info"%></td>
            <%end%>
         </tr>
         <% end %>
      </tbody>
   </table>
   <%= paginate @jobs , theme: 'my_custom_theme'%>
</div>
<hr>

job-application-manojsharma/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

job-application-manojsharma/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

job-application-manojsharma/app/views/static_pages/dashbord_users.html.erb
<h1>User Created</h1>
<%= paginate @users ,theme:'my_custom_theme' %>
<table class="table table-hover">
   <thead>
      <tr>
         <th>First Name</th>
         <th>Last Name</th>
         <th>Email</th>
         <th class="text-center">Address</th>
         <th>City</th>
         <th>User Role</th>
         <th colspan="3" class="text-center"> Options</th>
      </tr>
   </thead>
   <tbody>
      <% @users.each do |user| %>
      <tr>
         <td><%= user.first_name %></td>
         <td><%= user.last_name %></td>
         <td><%= user.email %></td>
         <td><%= user.address %></td>
         <td><%= user.city %></td>
         <td><%= user.user_role %></td>
         <td><%= link_to 'Show', user_profile_path(user.id),class:"btn btn-warning" %></td>
         <td><%= link_to 'Destroy', user_profile_path(user.id), method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger"%></td>
      </tr>
      <% end %>
   </tbody>
</table>
<%= paginate @users  ,theme:'my_custom_theme' %>
<%= link_to 'Back To Home', root_path ,class:"btn btn-info" %>

job-application-manojsharma/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

job-application-manojsharma/app/views/static_pages/home.html.erb
<div class="container">
   <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
         <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap"/>
         </svg>
         <span class="fs-4">Job Application</span>
      </a>
      <ul class="nav nav-pills">
         <li class="nav-item"><a href="/" class="nav-link" aria-current="page">Home</a></li>
         <li class="nav-item"><a href="/static_pages/help" class="nav-link">Help</a></li>
         <li class="nav-item"><a href="/static_pages/contact" class="nav-link">Contact</a></li>
         <li class="nav-item"><a href="/static_pages/about" class="nav-link">About</a></li>
         <%if signed_in? && current_user.admin==true %> 
         <li class="nav-item"><a href="/static_pages/dashbord_users" class="nav-link">User Dashbord</a></li>
         <%end%>
         <% if signed_in? %>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%= link_to "View Profile", user_profile_path(id:current_user.id),class:"dropdown-item" %>
               <%= link_to "Edit Profile", edit_user_registration_path,class:"dropdown-item" %>
            </ul>
         </li>
         <%end%>     
      </ul>
      <% if signed_in? %>
      <div class="col-md-3 text-end">
         <%= link_to "Sign out", destroy_user_session_path,class:"btn btn-primary",:method => :delete %>
      </div>
      <%else%>
      <div class="col-md-3 text-end">
         <button type="button" class="btn btn-outline-primary me-2"><a href="/users/sign_in" class="text-decoration-none">Sign In</a></button>
         <button type="button" class="btn btn-primary"><a href="/users/sign_up" class="text-white text-decoration-none">Sign up</a></button>
      </div>
      <%end%>
   </header>
</div>

<% if !user_signed_in? %>
  <%= render partial:"static_pages/carasole"%>
<% end%>

<%if user_signed_in?%>
  <% if current_user.admin? %>
    <h3> Welcome Admin </h3>
    <%= render partial:"static_pages/adminview", :locals => {:jobs => @jobs,:jobs_paginate_admin => @jobs_paginate_admin} %>
  <%else%>
    <%if current_user.user_role.include?"Job Seeker"%>
      <%= render partial:"static_pages/jobseekerview", :locals => {:jobs => @jobs,:jobs_paginate_jobseeker => @jobs_paginate_jobseeker} %>
    <% end%>
    <%if current_user.user_role.include?"Employer" %> 
      <h3> Welcome Employer</h3>
      <%= render partial:"static_pages/employerview", :locals => {:jobs => @jobs} %>
    <% end%>
  <%end%>
<%end%>